import type { Customer } from "./types";

export const seedCustomers: Customer[] = [
  {
    id: "cus_1048",
    name: "Maya Chen",
    email: "maya.chen@example.com",
    ltv: 1240,
    totalOrders: 8,
    lastOrderDate: "Today, 09:42",
    status: "VIP",
  },
  {
    id: "cus_1047",
    name: "Jon Bell",
    email: "jon.bell@example.com",
    ltv: 680,
    totalOrders: 4,
    lastOrderDate: "Yesterday",
    status: "VIP",
  },
  {
    id: "cus_1046",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@example.com",
    ltv: 245,
    totalOrders: 2,
    lastOrderDate: "Sep 28, 2026",
    status: "Standard",
  },
  {
    id: "cus_1045",
    name: "Theo Wright",
    email: "theo.wright@example.com",
    ltv: 420,
    totalOrders: 3,
    lastOrderDate: "Jun 18, 2026",
    status: "At-Risk",
  },
  {
    id: "cus_1044",
    name: "Priya Shah",
    email: "priya.shah@example.com",
    ltv: 95,
    totalOrders: 1,
    lastOrderDate: "Sep 22, 2026",
    status: "New",
  },
  { id: "cus_1043", name: "Marcus Lee", email: "marcus.lee@example.com", ltv: 510, totalOrders: 5, lastOrderDate: "Sep 20, 2026", status: "VIP" },
  { id: "cus_1042", name: "Nora Patel", email: "nora.patel@example.com", ltv: 310, totalOrders: 2, lastOrderDate: "Aug 14, 2026", status: "Standard" },
  { id: "cus_1041", name: "Elliot Park", email: "elliot.park@example.com", ltv: 155, totalOrders: 1, lastOrderDate: "Sep 30, 2026", status: "New" },
  { id: "cus_1040", name: "Camila Ruiz", email: "camila.ruiz@example.com", ltv: 760, totalOrders: 6, lastOrderDate: "Jul 02, 2026", status: "At-Risk" },
  { id: "cus_1039", name: "Oliver Grant", email: "oliver.grant@example.com", ltv: 275, totalOrders: 2, lastOrderDate: "Sep 11, 2026", status: "Standard" },
];
